module.exports = [
  { type: 'jpg',         header_info: 'FF D8 FF',                                    _length: 3  },
  { type: 'png',         header_info: '89 50 4E 47',                                 _length: 4  },
  { type: 'gif',         header_info: '47 49 46 38',                                 _length: 4  },
  { type: 'tif',         header_info: '49 49 2A 00',                                 _length: 4  },
  { type: 'bmp',         header_info: '42 4D',                                       _length: 2  },
  { type: 'dwg',         header_info: '41 43 31 30',                                 _length: 4  },
  { type: 'psd',         header_info: '38 42 50 53',                                 _length: 4  },
  { type: 'rtf',         header_info: '7B 5C 72 74 66',                              _length: 5  },
  { type: 'xml',         header_info: '3C 3F 78 6D 6C',                              _length: 5  },
  { type: 'html',        header_info: '68 74 6D 6C 3E',                              _length: 5  },
  { type: 'eml',         header_info: '44 65 6C 69 76 65 72 79 2D 64 61 74 65 3A',   _length: 14 },
  { type: 'dbx',         header_info: 'CF AD 12 FE C5 FD 74 6F',                     _length: 8  },
  { type: 'pst',         header_info: '21 42 44 4E',                                 _length: 4  },
  { type: 'xls,doc',     header_info: 'D0 CF 11 E0',                                 _length: 4  },
  { type: 'mdb',         header_info: '53 74 61 6E 64 61 72 64 20 4A',               _length: 10 },
  { type: 'wpd',         header_info: 'FF 57 50 43',                                 _length: 4  },
  { type: 'eps,ps',      header_info: '25 21 50 53 2D 41 64 6F 62 65',               _length: 10 },
  { type: 'pdf',         header_info: '25 50 44 46 2D 31 2E',                        _length: 7  },
  { type: 'qdf',         header_info: 'AC 9E BD 8F',                                 _length: 4  },
  { type: 'pwl',         header_info: 'E3 82 85 96',                                 _length: 4  },
  { type: 'zip',         header_info: '50 4B 03 04',                                 _length: 4  },
  { type: 'rar',         header_info: '52 61 72 21',                                 _length: 4  },
  { type: 'wav',         header_info: '57 41 56 45',                                 _length: 4  },
  { type: 'avi',         header_info: '41 56 49 20',                                 _length: 4  },
  { type: 'ram',         header_info: '2E 72 61 FD',                                 _length: 4  },
  { type: 'rm',          header_info: '2E 52 4D 46',                                 _length: 4  },
  { type: 'mpg',         header_info: '00 00 01 BA',                                 _length: 4  },
  { type: 'mpg',         header_info: '00 00 01 B3',                                 _length: 4  },
  { type: 'mov',         header_info: '6D 6F 6F 76',                                 _length: 4  },
  { type: 'asf',         header_info: '30 26 B2 75 8E 66 CF 11',                     _length: 8  },
  { type: 'mid',         header_info: '4D 54 68 64',                                 _length: 4  }
]
